version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    goamd64:
      - v2
      - v3

universal_binaries:
  - name_template: "{{.ProjectName}}_{{.Version}}"
    mod_timestamp: "{{ .CommitTimestamp }}"
    replace: true

release:
  github:
    owner: kaumnen
    name: cipr

brews:
  - homepage: https://github.com/kaumnen/homebrew-kaumnen
    tap:
      owner: kaumnen
      name: homebrew-kaumnen

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
